build:
	/Users/dima/Downloads/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang++ 2-async-await.cpp -std=c++2a -fcoroutines-ts -stdlib=libc++ -o 2-async-await && ./2-async-await
	/Users/dima/Downloads/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang++ 1-yield.cpp -std=c++2a -fcoroutines-ts -stdlib=libc++ -o 1-yield && ./1-yield
	/Users/dima/Downloads/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang++ 0-yield.cpp -std=c++2a -fcoroutines-ts -stdlib=libc++ -o 0-yield && ./0-yield
