// Generated by https://babeljs.io

"use strict";

var _marked = /*#__PURE__*/regeneratorRuntime.mark(createGenerator);

function createGenerator() {
  return regeneratorRuntime.wrap(function createGenerator$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          console.log("2");
          _context.next = 3;
          return;

        case 3:
          console.log("4");
          _context.next = 6;
          return;

        case 6:
        case "end":
          return _context.stop();
      }
    }
  }, _marked, this);
}

var c = createGenerator();
console.log("1");
c.next();
console.log("3");
c.next();
console.log("5");
c.next();